# Generated by Django 4.2.3 on 2023-07-11 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tarot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarotcard',
            name='number',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
