# Generated by Django 4.2.3 on 2023-07-11 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tarot', '0002_tarotcard_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarotcard',
            name='number',
            field=models.IntegerField(default=0),
        ),
    ]
